spring:
  application:
    name: "streetfootball"
  datasource:
    url: jdbc:postgresql://localhost:5432/streetfootball
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog.yaml
server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
